Updated for CKEditor 4.2
codeex/allMedias pull request #2
Opened 2013-09-19 17:50 UTC by howellcc

I fiddled with it till I got it working with CKEditor 4.2.

2019-03-23 19:24 UTC, Koraykanat requested changes

2019-03-23 19:24 UTC, Koraykanat commented on allmedias/lang/en.js
> +	allmedias: 'Insert All Medias',
İmages

2019-03-23 19:24 UTC, Koraykanat commented on allmedias/dialogs/allmedias.js
> -				if ( fakeImage && fakeImage.data( 'cke-real-element-type' ) && fakeImage.data( 'cke-real-element-type' ) == 'allMedias' ) {
Data

2019-04-17 01:10 UTC, merged

2019-04-17 01:10 UTC, codeex commented
Thanks you!